### ISSUE TITLE
Instructions to reproduce experiments

### ISSUE THREAD

**Issue by e-tornike** [C-anwoy/Cross-Task-ICL#1]
Hey,

nice work! Would it be possible to add instructions/scripts to reproduce the result files?

Cheers!

**Comment by C-anwoy** [comment]
Hello,

Sure! I will add scripts and instructions to reproduce the results. Will update the repo soon.

Thanks!

**Comment by e-tornike** [comment]
Hey, any updates on when this will be available?

**Comment by C-anwoy** [comment]
Hi @e-tornike,

We have added instructions and scripts to run our code. You should now be able to reproduce the experiments. **Please note that owing to the difference in GPUs we are using, the accuracy reported may differ by +/- 5 points for any source-target pair or for zero-shot, and hence the best source task may alter**. _However, the performance improvement percentages reported must remain almost the same, and even if the best source alters, the top-5 will remain consistent_. We had verified these on our end and the code is running fine for us.

Please be more specific in the issues you are facing if you are still not able to run, given the library function we used are mostly standard above Python 3.7 versions and also for the corresponding PyTorch and transformers library releases.

Thanks!

**Comment by C-anwoy** [comment]
@e-tornike Also please note that we have added `Eval.ipynb` notebook to compute accuracy based on exact match. Please respond to let us know if you can run the code now. We can then close this issue.

Thanks!

**Comment by e-tornike** [comment]
Thank you for updating the repository and for the clarification! I am able to run the scripts.
